In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import math
from torchvision import transforms, datasets
import torchvision
from torch.utils.data import DataLoader,Dataset
from PIL import Image

In [2]:
class DarkNet(nn.Module):
    def __init__(self):

        super(DarkNet, self).__init__()
        
        self.conv1 = nn.Sequential(nn.Conv2d(in_channels=3, out_channels=32, kernel_size=3, stride=1, padding=1, bias=False),\
                                   nn.BatchNorm2d(32),nn.LeakyReLU(0.1))
        self.pool1 = nn.MaxPool2d(2)
        self.conv2 = nn.Sequential(nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, stride=1, padding=1, bias=False),\
                                    nn.BatchNorm2d(64),nn.LeakyReLU(0.1))
        self.pool2 = nn.MaxPool2d(2)
        self.conv3 = nn.Sequential(nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, stride=1, padding=1, bias=False),\
                                   nn.BatchNorm2d(128),nn.LeakyReLU(0.1))
        self.conv4 = nn.Sequential(nn.Conv2d(in_channels=128, out_channels=64, kernel_size=1, stride=1, padding=0, bias=False),\
                                   nn.BatchNorm2d(64),nn.LeakyReLU(0.1))
        self.conv5 = nn.Sequential(nn.Conv2d(in_channels=64, out_channels=128, kernel_size=2, stride=1, padding=1, bias=False),\
                                   nn.BatchNorm2d(128),nn.LeakyReLU(0.1))
        self.pool5 = nn.MaxPool2d(2)
        self.conv6 = nn.Sequential(nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, stride=1, padding=1, bias=False),\
                                   nn.BatchNorm2d(256), nn.LeakyReLU(0.1))
        self.conv7= nn.Sequential(nn.Conv2d(in_channels=256, out_channels=128, kernel_size=1, stride=1, padding=0, bias=False),\
                                   nn.BatchNorm2d(128), nn.LeakyReLU(0.1))
        self.conv8 = nn.Sequential(nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, stride=1, padding=1, bias=False),\
                                   nn.BatchNorm2d(256), nn.LeakyReLU(0.1))
        self.pool8 = nn.MaxPool2d(2)
        self.conv9 = nn.Sequential(nn.Conv2d(in_channels=256, out_channels=512, kernel_size=3, stride=1, padding=1, bias=False),\
                                   nn.BatchNorm2d(512), nn.LeakyReLU(0.1))
        self.conv10 = nn.Sequential(nn.Conv2d(in_channels=512, out_channels=256, kernel_size=1, stride=1, padding=0, bias=False),\
                                    nn.BatchNorm2d(256), nn.LeakyReLU(0.1))
        self.conv11 = nn.Sequential(nn.Conv2d(in_channels=256, out_channels=512, kernel_size=3, stride=1, padding=1, bias=False),\
                                    nn.BatchNorm2d(512), nn.LeakyReLU(0.1))
        self.conv12 = nn.Sequential(nn.Conv2d(in_channels=512, out_channels=256, kernel_size=1, stride=1, padding=0, bias=False),\
                                    nn.BatchNorm2d(256), nn.LeakyReLU(0.1))
        self.conv13 = nn.Sequential(nn.Conv2d(in_channels=256, out_channels=512, kernel_size=3, stride=1, padding=1, bias=False),\
                                    nn.BatchNorm2d(512), nn.LeakyReLU(0.1))
        self.pool13 = nn.MaxPool2d(2)
        self.conv14 = nn.Sequential(nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=3, stride=1, padding=1, bias=False),\
                                    nn.BatchNorm2d(1024), nn.LeakyReLU(0.1))
        self.conv15 = nn.Sequential(nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=1, stride=1, padding=0, bias=False),\
                                    nn.BatchNorm2d(512), nn.LeakyReLU(0.1))
        self.conv16 = nn.Sequential(nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=3, stride=1, padding=1, bias=False),\
                                    nn.BatchNorm2d(1024), nn.LeakyReLU(0.1))
        self.conv17 = nn.Sequential(nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=1, stride=1, padding=0, bias=False),\
                                    nn.BatchNorm2d(512), nn.LeakyReLU(0.1))
        self.conv18 = nn.Conv2d(in_channels=512, out_channels=30, kernel_size=3, stride=1, padding=1, bias=False)
        self.pool18 = nn.AvgPool2d(7)
        
    def forward(self, x):
        x = self.conv1(x)
        x = self.pool1(x)
        x = self.conv2(x)
        x = self.pool2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.conv5(x)
        x = self.pool5(x)
        x = self.conv6(x)
        x = self.conv7(x)
        x = self.conv8(x)
        x = self.pool8(x)
        x = self.conv9(x)
        x = self.conv10(x)
        x = self.conv11(x)
        x = self.conv12(x)
        x = self.conv13(x)
        x = self.pool13(x)
        x = self.conv14(x)
        x = self.conv15(x)
        x = self.conv16(x)
        x = self.conv17(x)
        x = self.conv18(x)
        x = self.pool18(x)
        x = x.view(x.size(0), -1)
        return x
    

In [3]:
data_transform = transforms.Compose([
        transforms.RandomResizedCrop (224),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225])
    ])

train_dataset = torchvision.datasets.ImageFolder(root='/media/lulugay/PC/CCCV/',transform=data_transform)
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size = 32, shuffle=True, num_workers=12)
 
val_dataset = torchvision.datasets.ImageFolder(root='/media/lulugay/PC/CCCV/', transform=data_transform)
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size = 32, shuffle=True, num_workers=12)


In [4]:
print train_loader.dataset.class_to_idx

{'mid-long-boots': 14, 'hoodies': 9, 'Canvas-shoes': 1, 'trenchcoat': 25, 'shirt-dress': 19, 'volumn-skirt': 26, 'flat-sandals': 6, 'qipao': 18, 'slim-bottom-skirt': 22, 'heel-sandals': 8, 'Long-Jeans': 2, 'beidaiqun': 3, 'leather-loafer-shoes': 10, 'outdoor-xiaobao': 15, 'cardigans': 5, 'booties-short-boots': 4, 'outerwear-vest': 16, 'shorts': 20, 'women-Sports-jackets': 29, 'leisure-dress': 11, 'wallets': 28, 'slim-pants-leggings': 23, 'A-line-loose-dress': 0, 'pullover-tops': 17, 'waisted-dress': 27, 'leisure-pants': 12, 'fur': 7, 'shoulder-handbag': 21, 'longsleeve-dress-for-fall': 13, 'tank-strap-tops': 24}


In [5]:
model = DarkNet()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
loss_func = nn.CrossEntropyLoss()

In [6]:
    import time
    for epoch in range(1):
        batch_size_start = time.time()
        running_loss = 0.0
        for i, (inputs, labels) in enumerate(train_loader):
            inputs = Variable(inputs)
            print inputs.shape
            labels = Variable(labels)
            print labels
            optimizer.zero_grad()
            outputs = model(inputs)
            print outputs.shape
            loss = loss_func(outputs, labels)        #交叉熵
            loss.backward()
            optimizer.step()                          #更新权重
            running_loss += loss.data[0]
 
        print('Epoch [%d/%d], Loss: %.4f,need time %.4f'
                  % (epoch + 1, num_epochs, running_loss / (4000 / batch_size), time.time() - batch_size_start))


torch.Size([32, 3, 224, 224])
tensor([ 2, 15, 19,  2, 22,  4, 25,  1,  4, 21, 24, 10,  8, 28, 17, 16, 17, 20,
        24,  0, 16, 11, 18, 10, 24, 19, 27, 14, 18,  5, 23, 16])
torch.Size([32, 30])


/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:16: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  app.launch_new_instance()


torch.Size([32, 3, 224, 224])
tensor([27,  8, 25,  1,  4, 27, 17, 22, 18, 16, 18,  8,  8, 26, 27, 18, 15, 29,
         0,  6, 14, 13, 18, 28, 28, 12,  0,  4, 27,  7,  7,  1])
torch.Size([32, 30])
torch.Size([32, 3, 224, 224])
tensor([11,  0, 12, 15, 11, 13, 26,  6, 15, 29, 25,  9,  5, 29, 18,  7, 13, 22,
         4,  3, 15, 25, 25, 13,  2,  0, 20, 15, 23,  6,  6,  1])
torch.Size([32, 30])
torch.Size([32, 3, 224, 224])
tensor([16, 13, 26, 29, 27, 12, 21, 19, 22, 23, 12,  3, 14,  5, 17,  6, 12, 13,
        25, 15, 11,  6,  6,  0, 29,  2, 19,  3, 22,  0, 20, 19])
torch.Size([32, 30])
torch.Size([32, 3, 224, 224])
tensor([ 9, 29, 28,  7, 17, 24, 19,  3,  5, 27, 11, 28, 10, 13, 23,  5,  3, 10,
         4, 16,  0, 17, 12, 29, 19,  9, 18, 25,  2, 22, 15, 25])
torch.Size([32, 30])
torch.Size([32, 3, 224, 224])
tensor([ 8, 14,  1, 27, 12,  7, 27, 12,  1,  4,  7, 29, 17,  5, 29, 21, 15, 19,
         5, 20, 10, 20, 26, 28, 29,  1, 20, 12, 15,  3, 19, 16])
torch.Size([32, 30])
torch.Size([32, 3, 2

Process Process-7:
Process Process-6:
Process Process-10:
Process Process-9:
Process Process-12:
Process Process-11:
Process Process-4:
Process Process-5:
Process Process-8:
Traceback (most recent call last):
Process Process-3:
Traceback (most recent call last):
Process Process-2:
Process Process-1:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258

KeyboardInterrupt: 